version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
        context: ./dolibarr-yuupee
        dockerfile: Dockerfile
    depends_on:
        - db
    volumes:
      - ./dolibarr-yuupee:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    build:
        context: ./script
        dockerfile: Dockerfile
    restart: always
    volumes:
        - ./script/mysql:/var/lib/mysql
    ports:
        - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db